<?php
define('WOODPECKER_DAILY_ARCHVIES', __('Daily Archives', 'woodpecker'));
define('WOODPECKER_MONTHLY_ARCHIVES', __('Monthly Archives', 'woodpecker'));
define('WOODPECKER_YEARLY_ARCHIVES', __('Yearly Archives', 'woodpecker'));
define('WOODPECKER_BLOG_ARCHIVES', __('Blog Archives', 'woodpecker'));
define('WOODPECKER_OLDER_POSTS', __('&larr; Older Posts', 'woodpecker'));
define('WOODPECKER_NEWER_POSTS', __('Newer posts &rarr;', 'woodpecker'));
define('WOODPECKER_RETURN_TO_PREVIUS', __('Return to %s', 'woodpecker'));
define('WOODPECKER_BY_AUTHOR', __('By %2$s', 'woodpecker'));
define('WOODPECKER_VIEW_ALL_POST_BY', __('View all posts by %s', 'woodpecker'));
define('WOODPECKER_PUBLISHED_BY_AUTHOR', __('Published %2$s', 'woodpecker'));
define('WOODPECKER_FULL_SIZE_IS_PIXEL', __('Full size is %s pixels', 'woodpecker'));
define('WOODPECKER_LINK_TO_FULL_SIZE', __('Link to full-size image', 'woodpecker'));
define('WOODPECKER_EDIT', __('Edit', 'woodpecker'));
define('WOODPECKER_BOOKMARK_THE', __('Bookmark the', 'woodpecker'));
define('WOODPECKER_PERMALINK', __('&nbsp;permalink', 'woodpecker'));
define('WOODPECKER_PAGES_COLON', __('Pages:', 'woodpecker'));
define('WOODPECKER_AUTHOR_ARCHIVES', __('Author Archives: %s', 'woodpecker'));
define('WOODPECKER_ABOUT_AUTHOR', __('About %s', 'woodpecker'));
define('WOODPECKER_HOME', __('Home', 'woodpecker'));
define('WOODPECKER_SORRY_NO_POST_MATCHED_YOUR_CRETERIA', __('Sorry no post matched your criteria', 'woodpecker'));
define('WOODPECKER_PRIMARY_WIDGET', __('Primary Widget Area', 'woodpecker'));
define('WOODPECKER_THE_PRIMARY_WIDGET', __('The primary widget area', 'woodpecker'));
define('WOODPECKER_SECONDRY_WIDGET', __('Secondary Widget Area', 'woodpecker'));
define('WOODPECKER_THE_SECONDRY_WIDGET', __('The secondary widget area', 'woodpecker'));
define('WOODPECKER_FIRST_FOOTER_WIDGET', __('First Footer Widget Area', 'woodpecker'));
define('WOODPECKER_THE_FIRST_FOOTER_WIDGET', __('The first footer widget area', 'woodpecker'));
define('WOODPECKER_SECONDRY_FOOTER_WIDGET', __('Second Footer Widget Area', 'woodpecker'));
define('WOODPECKER_THE_SECONDRY_FOOTER_WIDGET', __('The second footer widget area', 'woodpecker'));
define('WOODPECKER_THIRD_FOOTER_WIDGET', __('Third Footer Widget Area', 'woodpecker'));
define('WOODPECKER_THE_THIRD_FOOTER_WIDGET', __('The third footer widget area', 'woodpecker'));
define('WOODPECKER_FOURTH_FOOTER_WIDGET', __('Fourth Footer Widget Area', 'woodpecker'));
define('WOODPECKER_THE_FOURTH_FOOTER_WIDGET', __('The fourth footer widget area', 'woodpecker'));
define('WOODPECKER_MAIN_MENU', __('Main Menu', 'woodpecker'));
?>